# Packages
```{r}
library(ggplot2) # Plots
library(magrittr) # Pipe function
library(dplyr)
library(tidyverse) # Functions for tidying data
library(GGally) # Helpful EDA plot function
library(naniar)
library(plotly) # Hover text in plots
library(XML) # xml_Parse
library(rvest) # html_table, html_node
library(RCurl) # getURL
library(stringi)
library(stringr) # Remove sub-string from a string
library(RJSONIO)
library(jsonlite)
library(naniar) # common NA removal functions
library(e1071)
library(class)
library(caret)

# Downloading APIs
library(openair)
library(quantmod)
library(treebase)
library(twitteR)
library(rtweet)
library(WDI)
library(rOpenSci)

# Data sets
library(nycflights13)

```

# Fcuntions
```{r}
parse_number() # pulls number from the string ($500)
dim() # counts how many lines a data frame has
summary()
str()
names() # shows column headers of a data frame
grep() # looks for a string in a dataset`
writeLines()
sort() # shows the data type for each column and the data type
paste0() # concatenate vector after converting to character
rbind_pages() # combine multple data frames into one
Sys.sleep() # suspends execution for a specific interval in seconds
tail() # show the last n rows
droplevels() # drop the specified level from a factor
sample()
knn() # k nearest neighbor
knn.cv() # internal cross validation
scale() # standardizes the scale of the axis. Used with knn.
table() # creates a table from inputs
confusionMatrix() # creates a confusion matrix from your table of data.
colMeans() # finds the mean of each column
naiveBayes()
dnorm() # density distribution function given mean and sd
```