---
title: "Unit 3"
author: "CDHolmes"
date: "11/9/2021"
output: html_document
---
## Packages
```{r}
library(ggplot2)
library(magrittr) # pipe function
library(dplyr)
library(tidyverse)
library(GGally)
library(nycflights13)
library(naniar) # function for missing values chart gg_miss_var
library(plotly)
```

## Standard Functions
```{r}
### filter() - Pick observations by their values.
### group_by() - Group the data by the values in a(n) specific column(s)
### arrange() - Reorder the rows.
### select() - Pick variables by their names.
### mutate() - Create new variables with functions of existing variables.
### summarize() - Collapse many values down to a single summary.
```

## filter()
```{r}
# Both of these will filter on compact
# mpg[mpg$class == "compact",] # nolint
# mpg %>% filter(class == "compact") # nolint

mpg %>%
    filter(class == "compact") %>%
    ggplot(aes(x = cty)) +
    geom_histogram() +
    ggtitle("City MPG")
```

## missing values
```{r}
# Missing/unknown values in R are recorded as NA
x <- NA
is.na(x)

# Dataframe for the Example
age <- c(22, 21, NA, 24, 19, 20, 23)
yrs_math_ed <- c(4, 5, NA, 2, 5, 3, 5)
names <- c("Mary", "Martha", "Rosy", "Kim", "Kristen", "Amy", "Sam")
subject <- c("English", "Math", NA, "Sociology", "Math", "Music", "Dance")
df <- data.frame(Age = age, Years = yrs_math_ed, Name = names, Major = subject)
df

is.na(df$Years)
is.na(df$Name)
is.na(df$Major)
```

```{r}
df %>% filter(!is.na(Years)) # Filter out rows with missing Years
```

## Arranging
```{r}
mpg %>%
    arrange(manufacturer) %>%
    print(n = 30)
```

```{r}
mpg %>%
    arrange(manufacturer, cty) %>%
    print(n = 30)
```

```{r}
# Dataframe for the Example
age <- c(22, 21, NA, 24, 19, 20, 23)
yrs_math_ed <- c(4, 5, NA, 2, 5, 3, 5)
names <- c("Mary", "Martha", "Rosy", "Kim", "Kristen", "Amy", "Sam")
subject <- c("English", "Math", NA, "Sociology", "Math", "Music", "Dance")
df <- data.frame(Age = age, Years = yrs_math_ed, Name = names, Major = subject)
df
# Sort on a column with no NAs
df %>% arrange(df$Name)

# Sort on a column with NAs
df %>% arrange(df$Age)

# NA end up at the end of the list when sorted on column with NAs.
```

## Select v. Filter
```{r}
# chooses rows with year < 2000
mpg %>% filter(year < 2000)

# chooses the columns class, city, hwy
mpg %>% select(class, cty, hwy)
```

```{r}
# NEW PACKAGE! Ggally

# chooses the columns class, city, hwy to use with ggpairs
mpg %>%
    select(class, cty, hwy) %>%
    ggpairs(aes(color = class))
```

## FIFA example
```{r}
fifa <- read.csv("C:/Users/corey/OneDrive/Documents/GitHub/MSDS_6306_Doing-Data-Science/Unit 3/FIFA Players.csv", header = TRUE)

head(fifa)
fifa %>%
    select(Finishing, BallControl, ShotPower) %>%
    ggpairs()

# Finising Score v. Ball Control, v Shot Power v. Footed for all players
fifa %>%
    filter(Preferred.Foot == "Right" | Preferred.Foot == "Left") %>%
    select(Finishing, BallControl, ShotPower, Preferred.Foot) %>%
    ggpairs(aes(color = Preferred.Foot))

# Right Strikers
fifa %>%
    filter(Preferred.Foot == "Right" | Preferred.Foot == "Left" & Position == "RS") %>%
    select(Finishing, BallControl, ShotPower, Preferred.Foot) %>%
    ggpairs(aes(color = Preferred.Foot))

# Left Strikers
fifa %>%
    filter(Preferred.Foot == "Right" | Preferred.Foot == "Left" & Position == "LS") %>%
    select(Finishing, BallControl, ShotPower, Preferred.Foot) %>%
    ggpairs(aes(color = Preferred.Foot))
```

## mutate()
```{r}
## the mutate does not get added to original table. A new table must be created.
mpg_diff <- mpg %>% mutate(diffHC = hwy - cty)

mpg
mpg_diff

mpg %>%
    mutate(diffHC = hwy - cty) %>%
    ggplot(aes(x = displ, y = diffHC)) +
    geom_point()

## add color by class
mpg %>%
    mutate(diffHC = hwy - cty) %>%
    ggplot(aes(x = displ, y = diffHC, color = class)) +
    geom_point()

## add color by model
mpg %>%
    mutate(diffHC = hwy - cty) %>%
    ggplot(aes(x = displ, y = diffHC, color = model)) +
    geom_point()
```

## group_by()
```{r}
# class
mpg %>%
    group_by(class) %>%
    summarize(meanCTY = mean(cty), count = n())

# class and model
mpg %>%
    group_by(class, model) %>%
    summarize(meanCTY = mean(cty), count = n())

# Chapter 2 example
mpg %>%
    group_by(class) %>%
    summarize(sum(cty))

# FIFA example

# With missing Position
fifa %>%
    group_by(Position) %>%
    summarize(meanBC = mean(BallControl), count = n()) %>%
    print(n = 28)

# With missing values in BC removed in mean call
fifa %>%
    group_by(Position) %>%
    summarize(meanBC = mean(BallControl, na.rm = TRUE), count = n()) %>%
    print(n = 28)

# With missing values removed before mean call
fifa %>%
    filter(!is.na(BallControl)) %>%
    group_by(Position) %>%
    summarize(meanBC = mean(BallControl), count = n()) %>%
    print(n = 28)

# Bar Chart to visualize ball control by position
fifa %>%
    filter(!is.na(BallControl)) %>%
    group_by(Position) %>%
    summarize(meanBC = mean(BallControl), count = n()) %>%
    ggplot(aes(x = Position, y = meanBC)) +
    geom_col()

# Arrange to see in order
fifa %>%
    filter(!is.na(BallControl)) %>%
    group_by(Position) %>%
    summarize(meanBC = mean(BallControl), count = n()) %>%
    arrange(meanBC) %>%
    print(n = 28)
```


## factor

### Examples
```{r}
# Dataframe for the Example
age <- c(22, 21, NA, 24, 19, 20, 23)
yrs_math_ed <- c(4, 5, NA, 2, 5, 3, 5)
names <- c("Mary", "Martha", "Rosy", "Kim", "Kristen", "Amy", "Sam")
subject <- c("English", "Math", NA, "Sociology", "Math", "Music", "Dance")
df <- data.frame(Age = age, Years = yrs_math_ed, Name = names, Major = subject)
df
str(df)
# Names and Subjects are already factors.


# mpg Example

summary(mpg$cyl)

mpg %>%
    ggplot(aes(x = hwy, y = cty, color = cyl)) +
    geom_point()

mpg %>%
    ggplot(aes(x = hwy, y = cty, color = as.factor(cyl))) +
    geom_point()

cylFact <- factor(mpg$cyl)
cylFact
# replace the values with a new value
levels(cylFact) <- c("Four", "Five", "Six", "Eight")
cylFact

# change the label of the values
cylFact <- factor(mpg$cyl, labels = c("Four", "Five", "Six", "Eight"))
cylFact

mpg %>%
    mutate(cyl_Factor = cylFact) %>%
    ggplot(aes(x = hwy, y = cty, color = cyl_Factor)) +
    geom_point()
```

## FIFA example
```{r}
# Bar Chart to visualize ball control by position in order of meanBC

# arrange (order) by meanBC
fifa_BC <- fifa %>%
    filter(!is.na(BallControl)) %>%
    group_by(Position) %>%
    summarize(meanBC = mean(BallControl), count = n()) %>%
    arrange(meanBC) %>%
    print(n = 28)

# reorder level of Postition factor
fifa_BC$Position <- factor(fifa_BC$Position, level = fifa_BC$Position[order(fifa_BC$meanBC)])

# column plot of ordered results
fifa_BC %>% ggplot(aes(x = Position, y = meanBC)) +
    geom_col()
```

## Cut Example with mpg data
```{r}
displ_factor <- cut(mpg$displ,
    breaks = c(1, 4, 6, 8),
    labels = c("Low", "Medium", "High")
)

mpg %>%
    mutate(displ_Factor = displ_factor) %>%
    ggplot(aes(x = hwy, y = cty, color = displ_factor)) +
    geom_point() +
    ggtitle("City MPG v. Highway MPG by Displacement")
```

## Categorical vs. Continueous
```{r}
# categorical
totals <- count(mpg, class)
totals

mpg %>%
    ggplot(aes(x = class, fill = class)) +
    geom_bar() +
    geom_text(aes(class, n + 2, label = n, fill = NULL), data = totals)

# continuous
mpg %>%
    ggplot(aes(x = cty, fill = class)) +
    geom_histogram()

mpg %>%
    ggplot(aes(x = cty, color = class)) +
    geom_freqpoly()

mpg %>%
    ggplot(aes(y = cty, color = class)) +
    geom_boxplot()

mpg %>%
    ggplot(aes(x = cty, color = class)) +
    geom_histogram() +
    facet_grid(rows = vars(class))
```

## Diamonds Dataset
```{r}
str(diamonds)

diamonds %>%
    ggplot(aes(x = price, fill = color)) +
    geom_histogram()

diamonds %>%
    ggplot(aes(x = carat, fill = color)) +
    geom_histogram()

diamonds %>%
    ggplot(aes(x = depth, fill = cut)) +
    geom_histogram()

diamonds %>%
    ggplot(aes(x = carat, y = price, color = color)) +
    geom_point() +
    facet_wrap(~clarity)
```

## Center and Spread
```{r}
mpg %>%
    group_by(class) %>%
    summarize(
        mean = mean(cty),
        sd = sd(cty),
        median = median(cty),
        range = max(cty) - min(cty),
        IQR = IQR(cty),
        count = n()
    )
```

## Missing Values
```{r}
df <- data.frame(x = c(1, 2, 3, 4), y = c(3, 4, 5, 6), z = c(1, 2, 3, 14))
df
sapply(df, function(x) mean(x))

# Toy Example
# Bring in MissingValueToy.csv as ’a’
a <- read.csv(file.choose(), header = TRUE)
# count missing values in each column
s <- sapply(a, function(x) sum(is.na(x)))
# Make all missing values NA
str(a)
a$chars[6] <- NA
str(a)
a$chars <- as.character(a$chars)
str(a)

gg_miss_var(a)

# Fifa
gg_miss_var(fifa[, 1:40]) + ylim(0, 75)

gg_miss_var(fifa[, 41:89]) + ylim(0, 75)

# mpg

gg_miss_var(mpg) + ylim(0, 10)

sapply(mpg, function(x) sum(is.na(x)))

# nycflights13
library(nycflights13)
gg_miss_var(flights)
sapply(flights, function(x) sum(is.na(x)))
```

## Question from material
```{r}
diamonds
gg_miss_var(diamonds)
sapply(diamonds, function(x) sum(is.na(x)))

# Using the bottom portion of the question.
diamond_new <- diamonds %>% mutate(z_new = replace(z, z < 3 | z > 20, NA))
gg_miss_var(diamond_new)
sapply(diamond_new, function(x) sum(is.na(x)))
# z_new sum = 16585

# Using the top portion of the question.
diamond_new2 <- diamonds %>% mutate(z_new = replace(z, z == 0 | z > 20, NA))
gg_miss_var(diamond_new)
sapply(diamond_new2, function(x) sum(is.na(x)))
# z_new sum = 21

diamonds %>% ggplot(aes(x = z)) +
    geom_histogram()
diamond_new %>% ggplot(aes(x = z_new)) +
    geom_histogram()

# How many diamonds have z values greater than 4.
sapply(diamonds, function(x) sum(x > 4))
# z sum = 15020
# 2.DS answer shows 3. I can manually count more than 3 thouhg.
```

## Ouliers
```{r}
# Find unusual city mpg values
library(ploltly)
p <- mpg %>%
    ggplot(aes(x = cty)) +
    geom_histogram()
ggplotly(p)

# Find unusual city mpg values
library(ploltly)
p <- mpg %>%
    ggplot(aes(y = cty, label = model)) +
    geom_boxplot()
ggplotly(p)

# Find unusual arrival delay values
library(ploltly)
p <- flights %>% ggplot(aes(x = arr_delay)) +
    geom_histogram()
ggplotly(p)

# Find unusual arrival delay values
library(ploltly)
p <- flights %>%
    ggplot(aes(y = arr_delay)) +
    geom_boxplot()
ggplotly(p)



# Diamonds

# Find unusual carat values
library(plotly)
p <- diamonds %>% ggplot(aes(x = carat)) +
    geom_histogram()
ggplotly(p)

# Find unusual y values
p <- diamonds %>% ggplot(aes(x = y)) +
    geom_histogram()
ggplotly(p)

# Check if they are Potentially Errors or just Outliers.
diamonds %>%
    mutate(priceFact = cut(price, breaks = c(0, 2000, 10000, 15000, 19000), labels = c("Low", "Medium", "High", "Very High"))) %>%
    ggplot(aes(x = carat, fill = priceFact)) +
    geom_histogram()
```

## Covariation
```{r}
mpg %>%
    ggplot(aes(y = cty, color = class)) +
    geom_boxplot()

mpg %>%
    ggplot(aes(x = cty, color = class)) +
    geom_histogram() +
    facet_grid(rows = vars(class))

diamonds %>%
    mutate(priceFact = cut(price, breaks = c(0, 2000, 10000, 15000, 19000), labels = c("Low", "Medium", "High", "Very High"))) %>%
    ggplot(aes(x = carat, fill = priceFact)) +
    geom_histogram() +
    ylim(c(0, 200)) +
    facet_wrap(vars(priceFact))

p <- diamonds %>%
    count(color, cut) %>%
    ggplot(aes(x = color, y = cut)) +
    geom_tile(mapping = aes(fill = n))
ggplotly(p)


p <- fifa %>%
    filter(!is.na(BallControl)) %>%
    mutate(BallControlFact = cut(BallControl, breaks = c(0, 30, 60, 90, 100), labels = c("Very Low", "Low", "Medium", "High"))) %>%
    count(Position, BallControlFact) %>%
    ggplot(aes(x = Position, BallControlFact)) +
    geom_tile(mapping = aes(fill = n))
ggplotly(p)


mpg %>% ggplot(aes(x = hwy, y = cty)) +
    geom_point(color = "blue")
# note that color is not in an ”aes”
# function we are setting them manually.


flights %>%
    ggplot(aes(x = dep_delay, y = arr_delay)) +
    geom_boxplot(mapping = aes(group = cut_width(dep_delay, 50))) +
    xlim(c(0, 700))

mpg %>% ggplot(aes(x = displ, y = cty)) +
    geom_point(aes(color = class))

mpg %>%
    select(displ, hwy, class) %>%
    ggpairs(aes(color = class))

mpg %>%
    ggplot(aes(x = manufacturer, y = model)) +
    geom_tile()
```

## Example Diamond Data
```{r}
diamonds %>%
    select(price, carat, cut) %>%
    ggpairs(mapping = aes(color = cut))

diamonds %>%
    group_by(cut) %>%
    summarize(median = median(price))

diamonds %>%
    group_by(cut) %>%
    summarize(median = median(carat))

diamonds %>%
    ggplot(aes(x = carat, y = price)) +
    geom_point()

diamonds %>%
    ggplot(aes(x = carat, y = price)) +
    geom_point(aes(color = cut))

diamonds %>%
    mutate(lcarat = log(carat), lprice = log(price)) %>%
    ggplot(aes(x = lcarat, y = lprice)) +
    geom_point()

diamonds %>%
    mutate(lcarat = log(carat), lprice = log(price)) %>%
    ggplot(aes(x = lcarat, y = lprice)) +
    geom_point() +
    geom_smooth(method = "lm") +
    ylim(c(5.5, 10))
    
## How did we get here? I'm not seeing where fit was defined.
diamonds %>%
    mutate(resids = exp(fit$residuals)) %>%
    ggplot(aes(x = carat, y = resids)) +
    geom_point()

diamonds %>%
    mutate(resids = exp(fit$residuals)) %>%
    ggplot(aes(x = carat, y = resids, color = cut)) +
    geom_point()

diamonds %>%
    mutate(resids = exp(fit$residuals)) %>%
    ggplot(aes(y = resids, color = cut)) +
    geom_boxplot()

diamonds %>%
    mutate(resids = exp(fit$residuals)) %>%
    group_by(cut) %>%
    summarise(median = median(resids))
```