# Live Session 5

# Packages
```{r}
library(dplyr)
library(magrittr)
library(ggplot2)
library(mapproj)
library(plotly)
library(tidyr)
library(stringr)
```

# Question 1
## Import yob2016
```{r}
yob2016 <-
    as.data.frame(read.delim("C:\\Users\\corey\\OneDrive\\Documents\\GitHub\\MSDS_6306_Doing-Data-Science\\Unit 5\\yob2016.txt", head = FALSE))
head(yob2016)
str(yob2016)

## Tidy data
yob2016_df <- yob2016 %>% separate(V1, into = c("name", "gender", "count"))
yob2016_df$gender <- as.factor(yob2016_df$gender)

## Find duplicate name
grep("yyy", yob2016_df$name, ignore.case = TRUE)
yob2016_df$name[212]
dim(yob2016_df)
grep("Fionayyy", yob2016_df$name, ignore.case = TRUE)

## Remove duplicate name
y2016 <- yob2016_df %>% filter(str_detect(name, "yyy$", negate = TRUE))
dim(y2016)
grep("Fionayy", y2016$name, ignore.case = TRUE)

## yob2016 summary
summary(y2016)
```

# Question 2
```{r}
yob2015 <-
    as.data.frame(read.delim("C:\\Users\\corey\\OneDrive\\Documents\\GitHub\\MSDS_6306_Doing-Data-Science\\Unit 5\\yob2015.txt", head = FALSE))
head(yob2015)
str(yob2015)

## Tidy data
y2015 <- yob2015 %>% separate(V1, into = c("name", "gender", "count"))
y2015$gender <- as.factor(y2015$gender)
head(y2015)

## Show last 10 rows
tail(y2015, n = 10)

### They are all male. They all have a count of 5.

## Merge yob2016 and yob2015
final <- merge(y2015, y2016, by = c("name", "gender"))
names(final)[names(final) == "count.x"] <- "count_2015"
names(final)[names(final) == "count.y"] <- "count_2016"
final <-
    final %>%
    mutate(final, total = as.numeric(final$count_2015) +
        as.numeric(final$count_2016))

final <- final[order(-final$total),]

## Top 10 names
slice_max(final, final$total, n = 10)

## Top 10 female names
final_female <-
    final %>%
    filter(gender == "F", ignore.case = TRUE) %>%
    slice_max(total, n = 10)
final_female_names <- final_female %>% select(name)

write.csv(final_female_names, "C:\\Users\\corey\\OneDrive\\Documents\\GitHub\\Doing_Data_Science\\Unit-5\\Top_10_Female_Names", row.names = FALSE)
```