---
title: "Chapter 3 - Visualisations"
author: "cdholmes"
---

# Libraries
```{r}
library(ggplot2)
library(tibble)
library(tidyr)
library(readr)
library(purrr)
library(dplyr)
library(stringr)
library(forcats)
library(magrittr)
```

# Resources

## ggplot2 extensions gallary
## https://exts.ggplot2.tidyverse.org/gallery/

## Template
<DATA> %>% ggplot() +
  <GEOM_FUNCTION>(
     mapping = aes(<MAPPINGS>),
     stat = <STAT>, 
     position = <POSITION>
  ) +
  <COORDINATE_FUNCTION> +
  <FACET_FUNCTION>

# Content
```{r}
ggplot(data = mpg)

# Color
mpg %>% ggplot(aes(x = displ, y = hwy, color = class)) +
    geom_point()

# Size
mpg %>% ggplot(aes(x = displ, y = hwy, size = class)) +
    geom_point()

# Alpha
mpg %>% ggplot(aes(x = displ, y = hwy, alpha = class)) +
    geom_point()

# Shape
mpg %>% ggplot(aes(x = displ, y = hwy, shape = class)) +
    geom_point()

# Manual
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
# or
mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point(color = "blue")

mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point(size = 2)

# Stroke, border width
mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point(shape = 21, colour = "black",
        fill = "white", size = 5, stroke = 5)

# Facets wrap
mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point() +
    facet_wrap(~ class, nrow = 2)

mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point() +
    facet_wrap(~ class, ncol = 1)

# Facet grid
mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point() +
    facet_grid(drv ~ cyl)

mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point() +
    facet_grid(. ~ cyl)

mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point() +
    facet_grid(drv ~ .)

# geom_smooth
mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_smooth()

mpg %>% ggplot(aes(x = displ, y = hwy, color = drv)) +
    geom_smooth(aes(linetype = drv)) +
    geom_point()

# group
mpg %>% ggplot(aes(x = displ, y = hwy, group = drv)) +
    geom_smooth()

# filter with geom
mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE) +
    geom_point(aes(color = class))

# Don't show legend
mpg %>% ggplot(aes(x = displ, y = hwy, group = drv)) +
    geom_smooth(show.legend = FALSE)

mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point(stroke = 4) +
    geom_smooth(color = "blue", se = FALSE)

mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point(stroke = 4) +
    geom_smooth(aes(group = drv),color = "blue", se = FALSE)

# Bar Chart stat
diamonds %>% ggplot(aes(x = cut, y = stat(prop), group = 1)) +
    geom_bar()

# stat_summary
diamonds %>% ggplot(aes(x = cut, y = depth)) +
    stat_summary(
    fun.min = min,
    fun.max = max,
    fun = median
    )

diamonds %>% ggplot(aes(x = cut, y = price)) +
    stat_summary(aes(color = clarity),
    fun.min = min,
    fun.max = max,
    fun = median
    )

# geom_col
diamonds %>% ggplot(aes(x = cut, y = price)) +
    geom_col()

# stat dodge
diamonds %>% ggplot(aes(x = cut, fill = clarity)) +
    geom_bar(position = "dodge")

# stat jitter
mpg %>% ggplot(aes(x = displ, y = hwy)) +
    geom_point(position = "jitter")

# coord_flip
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
    geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
    geom_boxplot() +
    coord_flip()

# coord_quickmap sets the correct aspect ratio for maps
nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) +
    geom_polygon(fill = "white", colour = "black")

ggplot(nz, aes(long, lat, group = group)) +
    geom_polygon(fill = "white", colour = "black") +
    coord_quickmap()

# polar coordinates
bar <- ggplot(data = diamonds) +
    geom_bar(
        mapping = aes(x = cut, fill = cut),
        show.legend = FALSE,
        width = 1
    ) +
    theme(aspect.ratio = 1) +
    labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()

# coord_fixed & geom_abline
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
    geom_point() +
    geom_abline() +
    coord_fixed()
```

