---
title: "Plotting Shaded Critical Regions"
author: "Novin"
date: "11/04/2021"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plotting Shaded Critical Regions
## Drawing Density Curves and Shaded Regions

```{r}

# First let's look at a normal curve
# the function for generating values from the normal density is dnorm()
# by default dnorm() fits the density for a standard normal
dnorm(0) # the density of a standard normal at 0

# we can specify arguments for the mean and sd
dnorm(0, sd = 2) # density at x=0, for a normal with mean 0 but sd=2 instead of 1
dnorm(0, mean = 1) # density at x=0, for a normal with mean 1 and sd still 1
dnorm(0, 3, 2) # density at x=0, for a normal with mean 3 and sd 2

# dnorm() can take a vector of arguments
# use this to generate data for density plots
# first create x values, using seq, from -4 to 4 by .01 increments
x <- seq(-4, 4, by = .01)

# now we get normal density and we plot
y <- dnorm(x)
plot(x, y,
        main = "Standard Normal Density",
        type = "l",
        lwd = 1.5,
        col = "red",
        xlab = "X",
        ylab = "Y"
)

# we can follow a similar process for the t distribution using dt()
# however, dt() does NOT have a mean and sd, but requires a degrees of freedom
dt(0, 10)
dt(0, df = 10)
y2 <- dt(x, 10)
plot(x, y2,
        main = "Student t Density, 10 Degrees of Freedom",
        type = "l",
        lwd = 1.5,
        col = "blue",
        xlab = "X",
        ylab = "Y"
)

crit_norm <- qnorm(.975)
crit_t <- qt(.975, df = 10)

qnorm(.975)
qt(.975, df = 10)
pnorm(qnorm(.975))

# create a red and blue with transparency
# this allows us to plot overlapping shaded critical regions
redt <- rgb(1, 0, 0, max = 1, alpha = .5)
bluet <- rgb(0, 0, 1, max = 1, alpha = .5)

plot(x, y,
        main = "Standard Normal Density",
        type = "l",
        lwd = 1.5,
        col = "red",
        xlab = "X",
        ylab = "Y"
)

lines(x, y2,
        lwd = 1.5,
        col = "blue"
)

# add polygon segments and fill them in to depict shaded critical region
# The polygon draws a line through all points and connects them, then fills color
polygon(
        x = c(min(x), x[x <= -crit_norm], -crit_norm),
        y = c(0, y[x <= -crit_norm], 0),
        col = redt
)

polygon(
        x = c(crit_norm, x[x >= crit_norm], max(x)),
        y = c(0, y[x >= crit_norm], 0),
        col = redt
)

polygon(
        x = c(min(x), x[x <= -crit_t], -crit_t),
        y = c(0, y2[x <= -crit_t], 0),
        col = bluet
)

polygon(
        x = c(crit_t, x[x >= crit_t], max(x)),
        y = c(0, y2[x >= crit_t], 0),
        col = bluet
)
```

## Plotting the Comber Beach t Test
```{r}
# Vector of ages of patrons leaving Beach Comber at 7pm
ages <- c(25, 19, 37, 29, 40, 28, 31)

mean_value <- mean(ages) # mean of data, xbar
std_dev <- sd(ages) # sd of data
std_err <- sd(ages) / sqrt(length(ages)) # standard error for the sampling distribution of xbar

x <- seq(10, 32, by = .01) # sequence of X's for plotting null hypothesis that mu=21
y3 <- dnorm(x, mean = 21, sd = std_err)
y4 <- dt((x - 21) / std_err, df = 6) / std_err

# upper critical values for normal and t
u_norm <- crit_norm * std_err + 21
u_t <- crit_t * std_err + 21

# lower critical values for normal and t
l_norm <- -crit_norm * std_err + 21
l_t <- -crit_t * std_err + 21

# green transparent color for plotting the p-value
greent <- rgb(0, 1, 0, max = 1, alpha = .5)

# plot of the null hypothesis distribution (assumes mu=21)
# red assumes a normal distribution
# blue assumes a t distribution (the example we tried in class)
plot(x, y3,
        main = bquote(paste("Sampling Distributions for ", bar(x))),
        col = "red",
        type = "l",
        xlab = "Ages",
        ylab = "Density",
        lwd = 1.5
)

lines(x, y4, col = "blue", lwd = 1.5)

# shade in normal critical region for data
polygon(
        x = c(min(x), x[x <= l_norm], l_norm),
        y = c(0, y3[x <= l_norm], 0),
        col = redt
)

polygon(
        x = c(u_norm, x[x >= u_norm], max(x)),
        y = c(0, y3[x >= u_norm], 0),
        col = redt
)

# shade in t distribution critical region
polygon(
        x = c(min(x), x[x <= l_t], l_t),
        y = c(0, y4[x <= l_t], 0),
        col = bluet
)

polygon(
        x = c(u_t, x[x >= u_t], max(x)),
        y = c(0, y4[x >= u_t], 0),
        col = bluet
)

# add green line to show where our t-stat from the data falls under they null hypothesis
abline(v = mean_value, col = "green", lwd = 1.5)

# the green shaded region
# this corresponds to the p-value of about .0162
# t.test(ages,mu=21,alternative="two.sided")$p.value
polygon(
        x = c((42 - mean_value), x[x <= (42 - mean_value)], (42 - mean_value)),
        y = c(0, y4[x <= (42 - mean_value)], 0),
        col = greent
)

polygon(
        x = c(mean_value, x[x >= mean_value], max(x)),
        y = c(0, y4[x >= mean_value], 0),
        col = greent
)
```

